# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history_monthly.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(QtWidgets.QWidget):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1452, 901)
        Dialog.setStyleSheet("background:rgb(0,0,0);")
        self.widget_rms_1 = PlotWidget(Dialog)
        self.widget_rms_1.setGeometry(QtCore.QRect(20, 20, 1411, 271))
        self.widget_rms_1.setStyleSheet("background:rgb(0,0,0);")
        self.widget_rms_1.setObjectName("widget_rms_1")
        self.label_44 = QtWidgets.QLabel(self.widget_rms_1)
        self.label_44.setGeometry(QtCore.QRect(100, 20, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(222, 114, 94);")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.widget_rms_1)
        self.label_45.setGeometry(QtCore.QRect(80, 10, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background-color:rgba(9,9,255,0);\n"
"color:rgb(222, 114, 94);")
        self.label_45.setObjectName("label_45")
        self.label_50 = QtWidgets.QLabel(self.widget_rms_1)
        self.label_50.setGeometry(QtCore.QRect(80, 30, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(60, 114, 174);")
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.widget_rms_1)
        self.label_51.setGeometry(QtCore.QRect(100, 40, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(60, 114, 174);")
        self.label_51.setObjectName("label_51")
        self.comboBox = QtWidgets.QComboBox(self.widget_rms_1)
        self.comboBox.setGeometry(QtCore.QRect(1270, 10, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background:rgba(0,0,0,0); color: rgb(220,220,220);\n"
"border:0px inset gray;\n"
"border-radius:0px;")
        self.comboBox.setEditable(False)
        self.comboBox.setMaxVisibleItems(0)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(self.widget_rms_1)
        self.label.setGeometry(QtCore.QRect(1270, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("background:rgba(0,0,0,0);\n"
"color:rgb(220,220,220);")
        self.label.setObjectName("label")
        self.widget_rms_2 = PlotWidget(Dialog)
        self.widget_rms_2.setGeometry(QtCore.QRect(20, 310, 1411, 271))
        self.widget_rms_2.setStyleSheet("background:rgb(0,0,0);")
        self.widget_rms_2.setObjectName("widget_rms_2")
        self.label_52 = QtWidgets.QLabel(self.widget_rms_2)
        self.label_52.setGeometry(QtCore.QRect(80, 10, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("background-color:rgba(9,9,255,0);\n"
"color:rgb(222, 114, 94);")
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.widget_rms_2)
        self.label_53.setGeometry(QtCore.QRect(100, 40, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(60, 114, 174);")
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.widget_rms_2)
        self.label_54.setGeometry(QtCore.QRect(80, 30, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(60, 114, 174);")
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.widget_rms_2)
        self.label_55.setGeometry(QtCore.QRect(100, 20, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(222, 114, 94);")
        self.label_55.setObjectName("label_55")
        self.pushButton = QtWidgets.QPushButton(self.widget_rms_2)
        self.pushButton.setGeometry(QtCore.QRect(1190, 0, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background:rgba(60,114,174,0.5); color:rgb(220,220,220);")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.widget_rms_2)
        self.label_2.setGeometry(QtCore.QRect(1200, 0, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:rgba(0,0,0,0);\n"
"color:rgb(200,200,200);")
        self.label_2.setObjectName("label_2")
        self.widget_rms_4 = PlotWidget(Dialog)
        self.widget_rms_4.setGeometry(QtCore.QRect(20, 600, 1411, 291))
        self.widget_rms_4.setStyleSheet("background:rgb(0,0,0);")
        self.widget_rms_4.setObjectName("widget_rms_4")
        self.label_48 = QtWidgets.QLabel(self.widget_rms_4)
        self.label_48.setGeometry(QtCore.QRect(100, 20, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(222, 114, 94);")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.widget_rms_4)
        self.label_49.setGeometry(QtCore.QRect(80, 10, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(222, 114, 94);")
        self.label_49.setObjectName("label_49")
        self.label_59 = QtWidgets.QLabel(self.widget_rms_4)
        self.label_59.setGeometry(QtCore.QRect(100, 40, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(60, 114, 174);")
        self.label_59.setObjectName("label_59")
        self.label_58 = QtWidgets.QLabel(self.widget_rms_4)
        self.label_58.setGeometry(QtCore.QRect(80, 30, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(60, 114, 174);")
        self.label_58.setObjectName("label_58")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_rms_4)
        self.pushButton_2.setGeometry(QtCore.QRect(1190, 0, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background:rgba(60,114,174,0.5); color:rgb(220,220,220);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.widget_rms_4)
        self.label_3.setGeometry(QtCore.QRect(1200, 0, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:rgba(0,0,0,0);\n"
"color:rgb(200,200,200);")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_44.setText(_translate("Dialog", "Outside Temperature [Celsius]"))
        self.label_45.setText(_translate("Dialog", "▆"))
        self.label_50.setText(_translate("Dialog", "▆"))
        self.label_51.setText(_translate("Dialog", "Outside Humidity [Weight of Water Vapours]"))
        self.label.setText(_translate("Dialog", "Select Month"))
        self.label_52.setText(_translate("Dialog", "▆"))
        self.label_53.setText(_translate("Dialog", "Legacy Cost Control [만원]"))
        self.label_54.setText(_translate("Dialog", "▆"))
        self.label_55.setText(_translate("Dialog", "AI Cost Control [만원]"))
        self.pushButton.setText(_translate("Dialog", "45.0 %"))
        self.label_2.setText(_translate("Dialog", "Cost Saved Per Month"))
        self.label_48.setText(_translate("Dialog", "AI Energy Control [Gega Joule]"))
        self.label_49.setText(_translate("Dialog", "▆"))
        self.label_59.setText(_translate("Dialog", "Legacy Energy Control [Gega Joule]"))
        self.label_58.setText(_translate("Dialog", "▆"))
        self.pushButton_2.setText(_translate("Dialog", "45.0 %"))
        self.label_3.setText(_translate("Dialog", "Energy Saved Per Month"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
