# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_new.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1932, 1029)
        font = QtGui.QFont()
        font.setFamily("Candara")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:rgb(0,0,0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(37, 450, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_19.setObjectName("label_19")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(37, 800, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_24.setObjectName("label_24")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(37, 520, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_20.setObjectName("label_20")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(37, 310, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_17.setObjectName("label_17")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(37, 660, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_22.setObjectName("label_22")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(37, 590, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_21.setObjectName("label_21")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(37, 240, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_16.setObjectName("label_16")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(37, 730, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_23.setObjectName("label_23")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(37, 380, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_18.setObjectName("label_18")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(37, 870, 21, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_26.setObjectName("label_26")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(32, 140, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_38.setObjectName("label_38")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(160, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_40.setObjectName("label_40")
        self.outside_lbl = QtWidgets.QLabel(self.centralwidget)
        self.outside_lbl.setGeometry(QtCore.QRect(170, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.outside_lbl.setFont(font)
        self.outside_lbl.setStyleSheet("background-color:rgba(0,0,0,0); color:rgb(200,200,200);")
        self.outside_lbl.setObjectName("outside_lbl")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(150, 120, 711, 861))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget.setStyleSheet("QTableView {border:0px;}\n"
"QHeaderView::section:horizontal {margin-left: 1; border: 0px solid white; color:rgb(200,200,200); background:rgb(30,30,30)}")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(71)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget.verticalHeader().setMinimumSectionSize(25)
        self.widget_rms_2 = PlotWidget(self.centralwidget)
        self.widget_rms_2.setGeometry(QtCore.QRect(650, 390, 1251, 281))
        self.widget_rms_2.setStyleSheet("background:rgb(0,0,0);")
        self.widget_rms_2.setObjectName("widget_rms_2")
        self.label_52 = QtWidgets.QLabel(self.widget_rms_2)
        self.label_52.setGeometry(QtCore.QRect(80, 10, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setStyleSheet("background-color:rgba(9,9,255,0);\n"
"color:rgb(222, 114, 94);")
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.widget_rms_2)
        self.label_53.setGeometry(QtCore.QRect(100, 40, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(60, 114, 174);")
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.widget_rms_2)
        self.label_54.setGeometry(QtCore.QRect(80, 30, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(60, 114, 174);")
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.widget_rms_2)
        self.label_55.setGeometry(QtCore.QRect(100, 20, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(222, 114, 94);")
        self.label_55.setObjectName("label_55")
        self.widget_rms_1 = PlotWidget(self.centralwidget)
        self.widget_rms_1.setGeometry(QtCore.QRect(650, 100, 1251, 281))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        self.widget_rms_1.setFont(font)
        self.widget_rms_1.setStyleSheet("background:rgb(0,0,0);")
        self.widget_rms_1.setObjectName("widget_rms_1")
        self.label_44 = QtWidgets.QLabel(self.widget_rms_1)
        self.label_44.setGeometry(QtCore.QRect(100, 20, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(222, 114, 94);")
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.widget_rms_1)
        self.label_45.setGeometry(QtCore.QRect(80, 10, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background-color:rgba(9,9,255,0);\n"
"color:rgb(222, 114, 94);")
        self.label_45.setObjectName("label_45")
        self.label_50 = QtWidgets.QLabel(self.widget_rms_1)
        self.label_50.setGeometry(QtCore.QRect(80, 30, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(60, 114, 174);")
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.widget_rms_1)
        self.label_51.setGeometry(QtCore.QRect(100, 40, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(60, 114, 174);")
        self.label_51.setObjectName("label_51")
        self.widget_rms_4 = PlotWidget(self.centralwidget)
        self.widget_rms_4.setGeometry(QtCore.QRect(650, 680, 1251, 291))
        self.widget_rms_4.setStyleSheet("background:rgb(0,0,0);")
        self.widget_rms_4.setObjectName("widget_rms_4")
        self.label_48 = QtWidgets.QLabel(self.widget_rms_4)
        self.label_48.setGeometry(QtCore.QRect(100, 20, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(222, 114, 94);")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.widget_rms_4)
        self.label_49.setGeometry(QtCore.QRect(80, 10, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(222, 114, 94);")
        self.label_49.setObjectName("label_49")
        self.label_59 = QtWidgets.QLabel(self.widget_rms_4)
        self.label_59.setGeometry(QtCore.QRect(100, 40, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_59.setFont(font)
        self.label_59.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(60, 114, 174);")
        self.label_59.setObjectName("label_59")
        self.label_58 = QtWidgets.QLabel(self.widget_rms_4)
        self.label_58.setGeometry(QtCore.QRect(80, 30, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_58.setFont(font)
        self.label_58.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(60, 114, 174);")
        self.label_58.setObjectName("label_58")
        self.pushButton_date = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_date.setGeometry(QtCore.QRect(20, 20, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(20)
        self.pushButton_date.setFont(font)
        self.pushButton_date.setStyleSheet("border: 0px; color:rgb(255,255,255);")
        self.pushButton_date.setObjectName("pushButton_date")
        self.pushButton_time = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_time.setGeometry(QtCore.QRect(20, 70, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(24)
        self.pushButton_time.setFont(font)
        self.pushButton_time.setStyleSheet("border: 0px; color:rgb(255,255,255);")
        self.pushButton_time.setObjectName("pushButton_time")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(150, 20, 111, 61))
        self.label_39.setStyleSheet("border:0px; background:rgb(45,45,45);\n"
"border-radius: 10px;")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(280, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_41.setObjectName("label_41")
        self.outside_lbl_2 = QtWidgets.QLabel(self.centralwidget)
        self.outside_lbl_2.setGeometry(QtCore.QRect(290, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.outside_lbl_2.setFont(font)
        self.outside_lbl_2.setStyleSheet("background-color:rgba(0,0,0,0);color:rgb(200,200,200);")
        self.outside_lbl_2.setObjectName("outside_lbl_2")
        self.label_62 = QtWidgets.QLabel(self.centralwidget)
        self.label_62.setGeometry(QtCore.QRect(270, 20, 111, 61))
        self.label_62.setStyleSheet("border:0px; background:rgb(45,45,45);\n"
"border-radius: 10px;")
        self.label_62.setText("")
        self.label_62.setObjectName("label_62")
        self.pushButton_avg_floor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_avg_floor.setGeometry(QtCore.QRect(28, 142, 105, 71))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(20)
        self.pushButton_avg_floor.setFont(font)
        self.pushButton_avg_floor.setStyleSheet("border:0px;color:rgb(200,200,200); background:rgb(45,45,45);border-radius: 10px;")
        self.pushButton_avg_floor.setText("")
        self.pushButton_avg_floor.setObjectName("pushButton_avg_floor")
        self.pushButton_9_floor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9_floor.setGeometry(QtCore.QRect(33, 240, 95, 61))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.pushButton_9_floor.setFont(font)
        self.pushButton_9_floor.setStyleSheet("border:0px; color:rgb(200,200,200);background:rgb(45,45,45);border-radius: 10px;")
        self.pushButton_9_floor.setText("")
        self.pushButton_9_floor.setObjectName("pushButton_9_floor")
        self.pushButton_8_floor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8_floor.setGeometry(QtCore.QRect(33, 310, 95, 61))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.pushButton_8_floor.setFont(font)
        self.pushButton_8_floor.setStyleSheet("border:0px; color:rgb(200,200,200);background:rgb(45,45,45);border-radius: 10px;")
        self.pushButton_8_floor.setText("")
        self.pushButton_8_floor.setObjectName("pushButton_8_floor")
        self.pushButton_7_floor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7_floor.setGeometry(QtCore.QRect(33, 380, 95, 61))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.pushButton_7_floor.setFont(font)
        self.pushButton_7_floor.setStyleSheet("border:0px; color:rgb(200,200,200);background:rgb(45,45,45);border-radius: 10px;")
        self.pushButton_7_floor.setText("")
        self.pushButton_7_floor.setObjectName("pushButton_7_floor")
        self.pushButton_6_floor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6_floor.setGeometry(QtCore.QRect(33, 450, 95, 61))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.pushButton_6_floor.setFont(font)
        self.pushButton_6_floor.setStyleSheet("border:0px;color:rgb(200,200,200); background:rgb(45,45,45);border-radius: 10px;")
        self.pushButton_6_floor.setText("")
        self.pushButton_6_floor.setObjectName("pushButton_6_floor")
        self.pushButton_5_floor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5_floor.setGeometry(QtCore.QRect(33, 520, 95, 61))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.pushButton_5_floor.setFont(font)
        self.pushButton_5_floor.setStyleSheet("border:0px; color:rgb(200,200,200);background:rgb(45,45,45);border-radius: 10px;")
        self.pushButton_5_floor.setText("")
        self.pushButton_5_floor.setObjectName("pushButton_5_floor")
        self.pushButton_4_floor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4_floor.setGeometry(QtCore.QRect(33, 590, 95, 61))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.pushButton_4_floor.setFont(font)
        self.pushButton_4_floor.setStyleSheet("border:0px;color:rgb(200,200,200); background:rgb(45,45,45);border-radius: 10px;")
        self.pushButton_4_floor.setText("")
        self.pushButton_4_floor.setObjectName("pushButton_4_floor")
        self.pushButton_3_floor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3_floor.setGeometry(QtCore.QRect(33, 660, 95, 61))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.pushButton_3_floor.setFont(font)
        self.pushButton_3_floor.setStyleSheet("border:0px; color:rgb(200,200,200);background:rgb(45,45,45);border-radius: 10px;")
        self.pushButton_3_floor.setText("")
        self.pushButton_3_floor.setObjectName("pushButton_3_floor")
        self.pushButton_2_floor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2_floor.setGeometry(QtCore.QRect(33, 730, 95, 61))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.pushButton_2_floor.setFont(font)
        self.pushButton_2_floor.setStyleSheet("border:0px; color:rgb(200,200,200);background:rgb(45,45,45);border-radius: 10px;")
        self.pushButton_2_floor.setText("")
        self.pushButton_2_floor.setObjectName("pushButton_2_floor")
        self.pushButton_1_floor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1_floor.setGeometry(QtCore.QRect(33, 800, 95, 61))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.pushButton_1_floor.setFont(font)
        self.pushButton_1_floor.setStyleSheet("border:0px; color:rgb(200,200,200);background:rgb(45,45,45);border-radius: 10px;")
        self.pushButton_1_floor.setText("")
        self.pushButton_1_floor.setObjectName("pushButton_1_floor")
        self.pushButton_b1_floor = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_b1_floor.setGeometry(QtCore.QRect(33, 870, 95, 61))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.pushButton_b1_floor.setFont(font)
        self.pushButton_b1_floor.setStyleSheet("border:0px;color:rgb(200,200,200); background:rgb(45,45,45);border-radius: 10px;")
        self.pushButton_b1_floor.setText("")
        self.pushButton_b1_floor.setObjectName("pushButton_b1_floor")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(26, 140, 109, 811))
        self.label_2.setStyleSheet("border:2px solid gray;border-radius: 10px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(435, 90, 213, 31))
        self.pushButton.setStyleSheet("background-color:rgba(222, 114, 94,100);\n"
"color:rgb(222, 114, 94);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(222, 90, 213, 31))
        self.pushButton_2.setStyleSheet("background-color:rgba(60, 114, 174,100);\n"
"color:rgb(60, 114, 174);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_66 = QtWidgets.QLabel(self.centralwidget)
        self.label_66.setGeometry(QtCore.QRect(390, 20, 111, 61))
        self.label_66.setStyleSheet("border:0px; background:rgb(45,45,45);\n"
"border-radius: 10px;")
        self.label_66.setText("")
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.centralwidget)
        self.label_67.setGeometry(QtCore.QRect(510, 20, 111, 61))
        self.label_67.setStyleSheet("border:0px; background:rgb(45,45,45);\n"
";border-radius: 10px;")
        self.label_67.setText("")
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.centralwidget)
        self.label_68.setGeometry(QtCore.QRect(630, 20, 111, 61))
        self.label_68.setStyleSheet("border:0px; background:rgb(45,45,45);\n"
";border-radius: 10px;")
        self.label_68.setText("")
        self.label_68.setObjectName("label_68")
        self.label_69 = QtWidgets.QLabel(self.centralwidget)
        self.label_69.setGeometry(QtCore.QRect(750, 20, 111, 61))
        self.label_69.setStyleSheet("border:0px; background:rgb(45,45,45);\n"
";border-radius: 10px;")
        self.label_69.setText("")
        self.label_69.setObjectName("label_69")
        self.label_71 = QtWidgets.QLabel(self.centralwidget)
        self.label_71.setGeometry(QtCore.QRect(400, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_71.setFont(font)
        self.label_71.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(self.centralwidget)
        self.label_72.setGeometry(QtCore.QRect(520, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_72.setFont(font)
        self.label_72.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.centralwidget)
        self.label_73.setGeometry(QtCore.QRect(640, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_73.setFont(font)
        self.label_73.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.centralwidget)
        self.label_74.setGeometry(QtCore.QRect(760, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_74.setFont(font)
        self.label_74.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_74.setObjectName("label_74")
        self.outside_lbl_5 = QtWidgets.QLabel(self.centralwidget)
        self.outside_lbl_5.setGeometry(QtCore.QRect(400, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.outside_lbl_5.setFont(font)
        self.outside_lbl_5.setStyleSheet("background-color:rgba(0,0,0,0); color:rgb(200,200,200);")
        self.outside_lbl_5.setObjectName("outside_lbl_5")
        self.outside_lbl_6 = QtWidgets.QLabel(self.centralwidget)
        self.outside_lbl_6.setGeometry(QtCore.QRect(520, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.outside_lbl_6.setFont(font)
        self.outside_lbl_6.setStyleSheet("background-color:rgba(0,0,0,0); color:rgb(200,200,200);")
        self.outside_lbl_6.setObjectName("outside_lbl_6")
        self.outside_lbl_7 = QtWidgets.QLabel(self.centralwidget)
        self.outside_lbl_7.setGeometry(QtCore.QRect(650, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.outside_lbl_7.setFont(font)
        self.outside_lbl_7.setStyleSheet("background-color:rgba(0,0,0,0); color:rgb(200,200,200);")
        self.outside_lbl_7.setObjectName("outside_lbl_7")
        self.outside_lbl_8 = QtWidgets.QLabel(self.centralwidget)
        self.outside_lbl_8.setGeometry(QtCore.QRect(770, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.outside_lbl_8.setFont(font)
        self.outside_lbl_8.setStyleSheet("background-color:rgba(0,0,0,0); color:rgb(200,200,200);")
        self.outside_lbl_8.setObjectName("outside_lbl_8")
        self.label_75 = QtWidgets.QLabel(self.centralwidget)
        self.label_75.setGeometry(QtCore.QRect(1090, 20, 111, 61))
        self.label_75.setStyleSheet("border:2px solid grey; background:rgba(0,0,0,0);\n"
";border-radius: 10px;")
        self.label_75.setText("")
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.centralwidget)
        self.label_76.setGeometry(QtCore.QRect(1210, 20, 111, 61))
        self.label_76.setStyleSheet("border:2px solid grey; background:rgba(0,0,0,0);\n"
";border-radius: 10px;")
        self.label_76.setText("")
        self.label_76.setObjectName("label_76")
        self.label_77 = QtWidgets.QLabel(self.centralwidget)
        self.label_77.setGeometry(QtCore.QRect(1100, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_77.setFont(font)
        self.label_77.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_77.setObjectName("label_77")
        self.label_78 = QtWidgets.QLabel(self.centralwidget)
        self.label_78.setGeometry(QtCore.QRect(1220, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_78.setFont(font)
        self.label_78.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_78.setObjectName("label_78")
        self.outside_lbl_10 = QtWidgets.QLabel(self.centralwidget)
        self.outside_lbl_10.setGeometry(QtCore.QRect(1110, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.outside_lbl_10.setFont(font)
        self.outside_lbl_10.setStyleSheet("background-color:rgba(0,0,0,0); color:rgb(255,0,0);")
        self.outside_lbl_10.setObjectName("outside_lbl_10")
        self.outside_lbl_11 = QtWidgets.QLabel(self.centralwidget)
        self.outside_lbl_11.setGeometry(QtCore.QRect(1220, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.outside_lbl_11.setFont(font)
        self.outside_lbl_11.setStyleSheet("background-color:rgba(0,0,0,0); color:rgb(255,0,0);")
        self.outside_lbl_11.setObjectName("outside_lbl_11")
        self.widget_rms_0 = PlotWidget(self.centralwidget)
        self.widget_rms_0.setGeometry(QtCore.QRect(1250, 130, 461, 91))
        self.widget_rms_0.setStyleSheet("background:rgba(0,0,0,0);")
        self.widget_rms_0.setObjectName("widget_rms_0")
        self.label_97 = QtWidgets.QLabel(self.widget_rms_0)
        self.label_97.setGeometry(QtCore.QRect(100, 20, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_97.setFont(font)
        self.label_97.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(222, 114, 94);")
        self.label_97.setObjectName("label_97")
        self.label_98 = QtWidgets.QLabel(self.widget_rms_0)
        self.label_98.setGeometry(QtCore.QRect(80, 10, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_98.setFont(font)
        self.label_98.setStyleSheet("background-color:rgba(9,9,255,0);\n"
"color:rgb(222, 114, 94);")
        self.label_98.setObjectName("label_98")
        self.label_99 = QtWidgets.QLabel(self.widget_rms_0)
        self.label_99.setGeometry(QtCore.QRect(80, 30, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_99.setFont(font)
        self.label_99.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(60, 114, 174);")
        self.label_99.setObjectName("label_99")
        self.label_100 = QtWidgets.QLabel(self.widget_rms_0)
        self.label_100.setGeometry(QtCore.QRect(100, 40, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_100.setFont(font)
        self.label_100.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(60, 114, 174);")
        self.label_100.setObjectName("label_100")
        self.label_101 = QtWidgets.QLabel(self.widget_rms_0)
        self.label_101.setGeometry(QtCore.QRect(100, 60, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_101.setFont(font)
        self.label_101.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"color:rgb(100, 185, 68);")
        self.label_101.setObjectName("label_101")
        self.label_102 = QtWidgets.QLabel(self.widget_rms_0)
        self.label_102.setGeometry(QtCore.QRect(80, 50, 20, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_102.setFont(font)
        self.label_102.setStyleSheet("background-color:rgba(9,9,255,0);\n"
"color:rgb(100, 185, 68);")
        self.label_102.setObjectName("label_102")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(648, 89, 1261, 931))
        self.label.setStyleSheet("background:rgb(0,0,0);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_daily = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_daily.setGeometry(QtCore.QRect(870, 20, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.pushButton_daily.setFont(font)
        self.pushButton_daily.setStyleSheet("border:0px; color:rgb(200,200,200);background:rgb(45,45,45);border-radius: 10px;")
        self.pushButton_daily.setObjectName("pushButton_daily")
        self.pushButton_monthly = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_monthly.setGeometry(QtCore.QRect(980, 20, 101, 61))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(18)
        self.pushButton_monthly.setFont(font)
        self.pushButton_monthly.setStyleSheet("border:0px; color:rgb(200,200,200);background:rgb(45,45,45);border-radius: 10px;")
        self.pushButton_monthly.setObjectName("pushButton_monthly")
        self.label_79 = QtWidgets.QLabel(self.centralwidget)
        self.label_79.setGeometry(QtCore.QRect(900, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_79.setFont(font)
        self.label_79.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.centralwidget)
        self.label_80.setGeometry(QtCore.QRect(1010, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Digital-7 Mono")
        font.setPointSize(10)
        self.label_80.setFont(font)
        self.label_80.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_80.setObjectName("label_80")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1240, 970, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(120,120,120);")
        self.label_6.setObjectName("label_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(222, 120, 213, 24))
        self.pushButton_3.setStyleSheet("background-color:rgba(60, 114, 174,100);\n"
"color:rgb(60, 114, 174);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(435, 120, 213, 24))
        self.pushButton_4.setStyleSheet("background-color:rgba(222, 114, 94,100);\n"
"color:rgb(222, 114, 94);")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(29, 210, 103, 5))
        self.line.setStyleSheet("background-color: gray;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_visualblocker = QtWidgets.QLabel(self.centralwidget)
        self.label_visualblocker.setGeometry(QtCore.QRect(0, 0, 461, 1011))
        self.label_visualblocker.setStyleSheet("background:rgb(0,0,0);")
        self.label_visualblocker.setText("")
        self.label_visualblocker.setObjectName("label_visualblocker")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(290, 670, 75, 23))
        self.login_button.setStyleSheet("background-color:rgb(0,0,0); color: rgb(255,255,255); border: 1px solid gray;")
        self.login_button.setObjectName("login_button")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(260, 640, 111, 20))
        self.lineEdit_password.setStyleSheet("color: rgb(255,255,255);")
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.lineEdit_username = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_username.setGeometry(QtCore.QRect(260, 610, 111, 20))
        self.lineEdit_username.setStyleSheet("color: rgb(255,255,255);")
        self.lineEdit_username.setText("")
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.label_username = QtWidgets.QLabel(self.centralwidget)
        self.label_username.setGeometry(QtCore.QRect(180, 610, 91, 20))
        self.label_username.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(180, 640, 91, 20))
        self.label_password.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_password.setObjectName("label_password")
        self.pushButton_logout = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_logout.setGeometry(QtCore.QRect(1840, 20, 61, 61))
        self.pushButton_logout.setStyleSheet("border:0px; color:rgb(200,200,200);background:rgba(45,45,45,0);border-radius: 10px;")
        self.pushButton_logout.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_logout.setIcon(icon1)
        self.pushButton_logout.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_logout.setObjectName("pushButton_logout")
        self.pushButton_setting = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_setting.setGeometry(QtCore.QRect(1700, 20, 61, 61))
        self.pushButton_setting.setStyleSheet("border:0px; color:rgb(200,200,200);background:rgba(45,45,45,0);border-radius: 10px;")
        self.pushButton_setting.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_setting.setIcon(icon2)
        self.pushButton_setting.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_setting.setObjectName("pushButton_setting")
        self.pushButton_logout_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_logout_2.setGeometry(QtCore.QRect(1770, 20, 61, 61))
        self.pushButton_logout_2.setStyleSheet("border:0px; color:rgb(200,200,200);background:rgba(45,45,45,0);border-radius: 10px;")
        self.pushButton_logout_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("sleep.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_logout_2.setIcon(icon3)
        self.pushButton_logout_2.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_logout_2.setObjectName("pushButton_logout_2")
        self.enable_button = QtWidgets.QPushButton(self.centralwidget)
        self.enable_button.setGeometry(QtCore.QRect(290, 670, 75, 23))
        self.enable_button.setStyleSheet("background-color:rgb(0,0,0); color: rgb(255,255,255); border: 1px solid gray;")
        self.enable_button.setObjectName("enable_button")
        self.label_visualblocker2 = QtWidgets.QLabel(self.centralwidget)
        self.label_visualblocker2.setGeometry(QtCore.QRect(460, 0, 1471, 1011))
        self.label_visualblocker2.setText("")
        self.label_visualblocker2.setPixmap(QtGui.QPixmap("login_wallpaper.gif"))
        self.label_visualblocker2.setObjectName("label_visualblocker2")
        self.label_visualblocker3 = QtWidgets.QLabel(self.centralwidget)
        self.label_visualblocker3.setGeometry(QtCore.QRect(490, 90, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        self.label_visualblocker3.setFont(font)
        self.label_visualblocker3.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_visualblocker3.setObjectName("label_visualblocker3")
        self.label_visualblocker4 = QtWidgets.QLabel(self.centralwidget)
        self.label_visualblocker4.setGeometry(QtCore.QRect(550, 100, 801, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_visualblocker4.setFont(font)
        self.label_visualblocker4.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_visualblocker4.setObjectName("label_visualblocker4")
        self.label_visualblocker5 = QtWidgets.QLabel(self.centralwidget)
        self.label_visualblocker5.setGeometry(QtCore.QRect(1090, 140, 251, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        self.label_visualblocker5.setFont(font)
        self.label_visualblocker5.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.label_visualblocker5.setObjectName("label_visualblocker5")
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setGeometry(QtCore.QRect(1630, 20, 61, 61))
        self.pushButton_stop.setStyleSheet("border:0px; color:rgb(200,200,200);background:rgba(45,45,45,0);border-radius: 10px;")
        self.pushButton_stop.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_stop.setIcon(icon4)
        self.pushButton_stop.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(1560, 20, 61, 61))
        self.pushButton_start.setStyleSheet("border:0px; color:rgb(200,200,200);background:rgba(45,45,45,0);border-radius: 10px;")
        self.pushButton_start.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_start.setIcon(icon5)
        self.pushButton_start.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_start.setObjectName("pushButton_start")
        self.loading_lbl2 = QtWidgets.QLabel(self.centralwidget)
        self.loading_lbl2.setGeometry(QtCore.QRect(0, 0, 1931, 1011))
        self.loading_lbl2.setStyleSheet("background-color:rgb(0,0,0);")
        self.loading_lbl2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.loading_lbl2.setText("")
        self.loading_lbl2.setObjectName("loading_lbl2")
        self.loading_lbl = QtWidgets.QLabel(self.centralwidget)
        self.loading_lbl.setGeometry(QtCore.QRect(570, 200, 800, 600))
        self.loading_lbl.setText("")
        self.loading_lbl.setPixmap(QtGui.QPixmap("loading.gif"))
        self.loading_lbl.setObjectName("loading_lbl")
        self.loading_lbl3 = QtWidgets.QLabel(self.centralwidget)
        self.loading_lbl3.setGeometry(QtCore.QRect(150, 90, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.loading_lbl3.setFont(font)
        self.loading_lbl3.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.loading_lbl3.setObjectName("loading_lbl3")
        self.loading_lbl4 = QtWidgets.QLabel(self.centralwidget)
        self.loading_lbl4.setGeometry(QtCore.QRect(90, 80, 311, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        self.loading_lbl4.setFont(font)
        self.loading_lbl4.setStyleSheet("background-color:rgba(0,0,0,0); color: rgb(200,200,200);")
        self.loading_lbl4.setObjectName("loading_lbl4")
        self.label_visualblocker7 = QtWidgets.QLabel(self.centralwidget)
        self.label_visualblocker7.setGeometry(QtCore.QRect(1780, 950, 141, 41))
        self.label_visualblocker7.setStyleSheet("background-color:rgba(0,0,0,0);")
        self.label_visualblocker7.setText("")
        self.label_visualblocker7.setPixmap(QtGui.QPixmap("logo.png"))
        self.label_visualblocker7.setObjectName("label_visualblocker7")
        self.label_visualblocker6 = QtWidgets.QLabel(self.centralwidget)
        self.label_visualblocker6.setGeometry(QtCore.QRect(120, 60, 211, 41))
        self.label_visualblocker6.setText("")
        self.label_visualblocker6.setPixmap(QtGui.QPixmap("shinsegae-logo.png"))
        self.label_visualblocker6.setObjectName("label_visualblocker6")
        self.label_visualblocker8 = QtWidgets.QLabel(self.centralwidget)
        self.label_visualblocker8.setGeometry(QtCore.QRect(-300, -260, 500, 500))
        self.label_visualblocker8.setText("")
        self.label_visualblocker8.setPixmap(QtGui.QPixmap("cost.gif"))
        self.label_visualblocker8.setObjectName("label_visualblocker8")
        self.label_visualblocker9 = QtWidgets.QLabel(self.centralwidget)
        self.label_visualblocker9.setGeometry(QtCore.QRect(40, 520, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_visualblocker9.setFont(font)
        self.label_visualblocker9.setStyleSheet("color:rgb(200,200,200);")
        self.label_visualblocker9.setObjectName("label_visualblocker9")
        self.label_visualblocker10 = QtWidgets.QLabel(self.centralwidget)
        self.label_visualblocker10.setGeometry(QtCore.QRect(40, 560, 331, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_visualblocker10.setFont(font)
        self.label_visualblocker10.setStyleSheet("color:rgb(200,200,200);")
        self.label_visualblocker10.setObjectName("label_visualblocker10")
        self.setting_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.setting_tabWidget.setGeometry(QtCore.QRect(600, 180, 721, 481))
        self.setting_tabWidget.setStyleSheet("background-color:rgb(0,0,0); border: 0px solid gray;")
        self.setting_tabWidget.setObjectName("setting_tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_28 = QtWidgets.QLabel(self.tab)
        self.label_28.setGeometry(QtCore.QRect(170, 160, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(200,200,200);")
        self.label_28.setObjectName("label_28")
        self.radioButton = QtWidgets.QRadioButton(self.tab)
        self.radioButton.setGeometry(QtCore.QRect(320, 161, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setStyleSheet("color: rgb(200,200,200);")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_2.setGeometry(QtCore.QRect(400, 161, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setStyleSheet("color: rgb(200,200,200);")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_3.setGeometry(QtCore.QRect(480, 161, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setStyleSheet("color: rgb(200,200,200);")
        self.radioButton_3.setObjectName("radioButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 201, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("border: 1px solid gray;\n"
"color: rgb(200,200,200); ")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(40, 251, 641, 23))
        self.pushButton_6.setStyleSheet("color: rgb(200,200,200); ")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.setting_tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(280, 80, 171, 41))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("logo_2.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(200, 130, 321, 21))
        self.label_4.setStyleSheet("color: rgb(200,200,200);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(130, 150, 441, 21))
        self.label_5.setStyleSheet("color: rgb(200,200,200);")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(210, 170, 301, 21))
        self.label_7.setStyleSheet("color: rgb(200,200,200);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(50, 240, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(200,200,200);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(80, 270, 571, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(200,200,200);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(540, 300, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(200,200,200);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(510, 440, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(200,200,200);")
        self.label_11.setObjectName("label_11")
        self.setting_tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(280, 150, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(200,200,200);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(240, 190, 251, 21))
        self.label_13.setStyleSheet("color: rgb(200,200,200);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(210, 210, 311, 21))
        self.label_14.setStyleSheet("color: rgb(200,200,200);")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(260, 230, 201, 21))
        self.label_15.setStyleSheet("color: rgb(200,200,200);")
        self.label_15.setObjectName("label_15")
        self.label_25 = QtWidgets.QLabel(self.tab_3)
        self.label_25.setGeometry(QtCore.QRect(230, 250, 121, 21))
        self.label_25.setStyleSheet("color: rgb(200,200,200);")
        self.label_25.setObjectName("label_25")
        self.label_27 = QtWidgets.QLabel(self.tab_3)
        self.label_27.setGeometry(QtCore.QRect(360, 250, 121, 21))
        self.label_27.setStyleSheet("color: rgb(200,200,200);")
        self.label_27.setObjectName("label_27")
        self.setting_tabWidget.addTab(self.tab_3, "")
        self.setting_label2 = QtWidgets.QLabel(self.centralwidget)
        self.setting_label2.setGeometry(QtCore.QRect(590, 150, 741, 551))
        self.setting_label2.setStyleSheet("border: 2px solid gray;\n"
"background-color:rgb(0,0,0); ")
        self.setting_label2.setText("")
        self.setting_label2.setObjectName("setting_label2")
        self.setting_apply = QtWidgets.QPushButton(self.centralwidget)
        self.setting_apply.setGeometry(QtCore.QRect(1160, 670, 75, 23))
        self.setting_apply.setStyleSheet("border: 1px solid gray;\n"
"color: rgb(200,200,200);")
        self.setting_apply.setObjectName("setting_apply")
        self.setting_cancel = QtWidgets.QPushButton(self.centralwidget)
        self.setting_cancel.setGeometry(QtCore.QRect(1240, 670, 75, 23))
        self.setting_cancel.setStyleSheet("border: 1px solid gray;\n"
"color: rgb(200,200,200);")
        self.setting_cancel.setObjectName("setting_cancel")
        self.setting_label = QtWidgets.QLabel(self.centralwidget)
        self.setting_label.setGeometry(QtCore.QRect(1210, 160, 111, 20))
        self.setting_label.setStyleSheet("color: rgb(255,255,255);")
        self.setting_label.setObjectName("setting_label")
        self.pushButton_stop.raise_()
        self.pushButton_start.raise_()
        self.pushButton_logout_2.raise_()
        self.pushButton_logout.raise_()
        self.pushButton_setting.raise_()
        self.widget_rms_0.raise_()
        self.tableWidget.raise_()
        self.label_2.raise_()
        self.pushButton_b1_floor.raise_()
        self.pushButton_1_floor.raise_()
        self.pushButton_2_floor.raise_()
        self.pushButton_3_floor.raise_()
        self.pushButton_4_floor.raise_()
        self.pushButton_5_floor.raise_()
        self.pushButton_6_floor.raise_()
        self.pushButton_7_floor.raise_()
        self.pushButton_8_floor.raise_()
        self.pushButton_9_floor.raise_()
        self.pushButton_avg_floor.raise_()
        self.pushButton_time.raise_()
        self.label_62.raise_()
        self.label_39.raise_()
        self.label_19.raise_()
        self.label_24.raise_()
        self.label_20.raise_()
        self.label_17.raise_()
        self.label_22.raise_()
        self.label_21.raise_()
        self.label_16.raise_()
        self.label_23.raise_()
        self.label_18.raise_()
        self.label_26.raise_()
        self.label_38.raise_()
        self.label_40.raise_()
        self.outside_lbl.raise_()
        self.pushButton_date.raise_()
        self.label_41.raise_()
        self.outside_lbl_2.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_66.raise_()
        self.label_67.raise_()
        self.label_68.raise_()
        self.label_69.raise_()
        self.label_71.raise_()
        self.label_72.raise_()
        self.label_73.raise_()
        self.label_74.raise_()
        self.outside_lbl_5.raise_()
        self.outside_lbl_6.raise_()
        self.outside_lbl_7.raise_()
        self.outside_lbl_8.raise_()
        self.label_75.raise_()
        self.label_76.raise_()
        self.label_77.raise_()
        self.label_78.raise_()
        self.outside_lbl_10.raise_()
        self.outside_lbl_11.raise_()
        self.label.raise_()
        self.widget_rms_1.raise_()
        self.widget_rms_2.raise_()
        self.widget_rms_4.raise_()
        self.pushButton_daily.raise_()
        self.pushButton_monthly.raise_()
        self.label_79.raise_()
        self.label_80.raise_()
        self.label_6.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.line.raise_()
        self.label_visualblocker.raise_()
        self.login_button.raise_()
        self.lineEdit_password.raise_()
        self.lineEdit_username.raise_()
        self.label_username.raise_()
        self.label_password.raise_()
        self.enable_button.raise_()
        self.label_visualblocker2.raise_()
        self.label_visualblocker3.raise_()
        self.label_visualblocker4.raise_()
        self.label_visualblocker5.raise_()
        self.label_visualblocker7.raise_()
        self.label_visualblocker8.raise_()
        self.label_visualblocker9.raise_()
        self.label_visualblocker6.raise_()
        self.label_visualblocker10.raise_()
        self.loading_lbl2.raise_()
        self.loading_lbl.raise_()
        self.loading_lbl3.raise_()
        self.loading_lbl4.raise_()
        self.setting_label2.raise_()
        self.setting_tabWidget.raise_()
        self.setting_apply.raise_()
        self.setting_cancel.raise_()
        self.setting_label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.setting_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Building Energy Management System"))
        self.label_19.setText(_translate("MainWindow", "6F"))
        self.label_24.setText(_translate("MainWindow", "1F"))
        self.label_20.setText(_translate("MainWindow", "5F"))
        self.label_17.setText(_translate("MainWindow", "8F"))
        self.label_22.setText(_translate("MainWindow", "3F"))
        self.label_21.setText(_translate("MainWindow", "4F"))
        self.label_16.setText(_translate("MainWindow", "9F"))
        self.label_23.setText(_translate("MainWindow", "2F"))
        self.label_18.setText(_translate("MainWindow", "7F"))
        self.label_26.setText(_translate("MainWindow", "B1F"))
        self.label_38.setText(_translate("MainWindow", "Inside Temp"))
        self.label_40.setText(_translate("MainWindow", "Outside Temp"))
        self.outside_lbl.setText(_translate("MainWindow", "25.5 C"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "AC"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "STC"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "LTC"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "AC"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "STC"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "LTC"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "index_number"))
        self.label_52.setText(_translate("MainWindow", "▆"))
        self.label_53.setText(_translate("MainWindow", "Legacy Cost Control - 만원"))
        self.label_54.setText(_translate("MainWindow", "▆"))
        self.label_55.setText(_translate("MainWindow", "AI Cost Control - 만원"))
        self.label_44.setText(_translate("MainWindow", "Outside Temperature - C"))
        self.label_45.setText(_translate("MainWindow", "▆"))
        self.label_50.setText(_translate("MainWindow", "▆"))
        self.label_51.setText(_translate("MainWindow", "Outside Humidity - %"))
        self.label_48.setText(_translate("MainWindow", "AI Energy Control [Gega Joule]"))
        self.label_49.setText(_translate("MainWindow", "▆"))
        self.label_59.setText(_translate("MainWindow", "Legacy Energy Control [Gega Joule]"))
        self.label_58.setText(_translate("MainWindow", "▆"))
        self.pushButton_date.setText(_translate("MainWindow", "2017.05.01"))
        self.pushButton_time.setText(_translate("MainWindow", "02:00"))
        self.label_41.setText(_translate("MainWindow", "Outside Hum"))
        self.outside_lbl_2.setText(_translate("MainWindow", "25.5 C"))
        self.pushButton.setText(_translate("MainWindow", "A.I Prediction"))
        self.pushButton_2.setText(_translate("MainWindow", "Legacy"))
        self.label_71.setText(_translate("MainWindow", "Legacy Cost"))
        self.label_72.setText(_translate("MainWindow", "AI Cost"))
        self.label_73.setText(_translate("MainWindow", "Legacy Energy"))
        self.label_74.setText(_translate("MainWindow", "AI Energy"))
        self.outside_lbl_5.setText(_translate("MainWindow", "25.5 C"))
        self.outside_lbl_6.setText(_translate("MainWindow", "25.5 C"))
        self.outside_lbl_7.setText(_translate("MainWindow", "25.5 C"))
        self.outside_lbl_8.setText(_translate("MainWindow", "25.5 C"))
        self.label_77.setText(_translate("MainWindow", "AI Energy Save"))
        self.label_78.setText(_translate("MainWindow", "AI Cost Save"))
        self.outside_lbl_10.setText(_translate("MainWindow", "25.5 C"))
        self.outside_lbl_11.setText(_translate("MainWindow", "25.5 C"))
        self.label_97.setText(_translate("MainWindow", "Outside Temperature [Celsius]"))
        self.label_98.setText(_translate("MainWindow", "▆"))
        self.label_99.setText(_translate("MainWindow", "▆"))
        self.label_100.setText(_translate("MainWindow", "Outside Humidity [Weight of Water Vapours]"))
        self.label_101.setText(_translate("MainWindow", "Visitors [Percentage]"))
        self.label_102.setText(_translate("MainWindow", "▆"))
        self.pushButton_daily.setText(_translate("MainWindow", "Daily"))
        self.pushButton_monthly.setText(_translate("MainWindow", "Monthly"))
        self.label_79.setText(_translate("MainWindow", "Statistics"))
        self.label_80.setText(_translate("MainWindow", "Statistics"))
        self.label_6.setText(_translate("MainWindow", "TIme [Hours]"))
        self.login_button.setText(_translate("MainWindow", "Login"))
        self.label_username.setText(_translate("MainWindow", "USERNAME"))
        self.label_password.setText(_translate("MainWindow", "PASSWORD"))
        self.enable_button.setText(_translate("MainWindow", "Enable"))
        self.label_visualblocker3.setText(_translate("MainWindow", "WELCOME TO ARTIFICIAL INTELLIGENCE BASED"))
        self.label_visualblocker4.setText(_translate("MainWindow", "BUILDING ENERGY MANAGEMENT SYSTEM"))
        self.label_visualblocker5.setText(_translate("MainWindow", "POWERED BY AUTOSEMANTICS | VERSION 5.71"))
        self.loading_lbl3.setText(_translate("MainWindow", "LOADING"))
        self.loading_lbl4.setText(_translate("MainWindow", "PLEASE WAIT"))
        self.label_visualblocker9.setText(_translate("MainWindow", "LOGIN"))
        self.label_visualblocker10.setText(_translate("MainWindow", "PLEASE ENTER YOUR USERNAME AND PASSWORD"))
        self.label_28.setText(_translate("MainWindow", "Target Temperature :"))
        self.radioButton.setText(_translate("MainWindow", "23.5 C"))
        self.radioButton_2.setText(_translate("MainWindow", "24.0 C"))
        self.radioButton_3.setText(_translate("MainWindow", "24.5 C"))
        self.pushButton_5.setText(_translate("MainWindow", "Insert File"))
        self.setting_tabWidget.setTabText(self.setting_tabWidget.indexOf(self.tab), _translate("MainWindow", "General"))
        self.label_4.setText(_translate("MainWindow", "Specialist in Industrial Application of Artificial Intelligence​"))
        self.label_5.setText(_translate("MainWindow", "Seek to reduce the Maintenance Cost and increase the Production Efficiency"))
        self.label_7.setText(_translate("MainWindow", "through Industrial Application of Artificial Intelligence"))
        self.label_8.setText(_translate("MainWindow", "Artificial Intelligence based"))
        self.label_9.setText(_translate("MainWindow", "BUILDING ENERGY MANAGEMENT SYSTEM"))
        self.label_10.setText(_translate("MainWindow", "VERSION 5.71"))
        self.label_11.setText(_translate("MainWindow", "All rights reserved | AUTOSEMANTICS.INC"))
        self.setting_tabWidget.setTabText(self.setting_tabWidget.indexOf(self.tab_2), _translate("MainWindow", "About"))
        self.label_12.setText(_translate("MainWindow", "CONTACT US"))
        self.label_13.setText(_translate("MainWindow", "Room 805, Building 705, Hanyang University"))
        self.label_14.setText(_translate("MainWindow", "222 Wangsimni-ro, Seongdong-gu Seoul, 04763, Korea"))
        self.label_15.setText(_translate("MainWindow", "EMAIL: office@autosemantics.com"))
        self.label_25.setText(_translate("MainWindow", "Tel: +82-2-2282-0506"))
        self.label_27.setText(_translate("MainWindow", "Fax: +82-2-2282-0507"))
        self.setting_tabWidget.setTabText(self.setting_tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Contact"))
        self.setting_apply.setText(_translate("MainWindow", "Apply"))
        self.setting_cancel.setText(_translate("MainWindow", "Cancel"))
        self.setting_label.setText(_translate("MainWindow", "Configuration Panel"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
